--------------------------------------------------------
--  File created - Monday-November-01-2021   
--------------------------------------------------------
DROP TABLE "SYSTEM"."GS_EMPLOYER";
DROP TABLE "SYSTEM"."GS_EVENT";
DROP TABLE "SYSTEM"."GS_ATHÈTES";
DROP TABLE "SYSTEM"."GS_SPONSOR";
DROP TABLE "SYSTEM"."GS_TERRAINS";
--------------------------------------------------------
--  DDL for Table GS_EMPLOYER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GS_EMPLOYER" 
   (	"ID_EMPLOYE" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"SALAIRE" NUMBER, 
	"DATREC" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GS_EVENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GS_EVENT" 
   (	"CODE" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"DATEDEBUT" DATE, 
	"COLUMN1" DATE, 
	"TYPE" VARCHAR2(20 BYTE), 
	"NBPARTICIPANT" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GS_ATHÈTES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GS_ATHÈTES" 
   (	"ID_ATHLETE" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"AGE" NUMBER, 
	"FILIERE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GS_SPONSOR
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GS_SPONSOR" 
   (	"ID_SPONSOR" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"MONTANT" NUMBER, 
	"ADRESSMAIL" VARCHAR2(20 BYTE), 
	"TYPEDECONTRAT" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GS_TERRAINS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GS_TERRAINS" 
   (	"ID_TERRAIN" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"LIEU" VARCHAR2(20 BYTE), 
	"CAPACITE" NUMBER, 
	"ETAT" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.GS_EMPLOYER
SET DEFINE OFF;
Insert into SYSTEM.GS_EMPLOYER (ID_EMPLOYE,NOM,PRENOM,SALAIRE,DATREC) values ('AM2','yassine','aaa',2000,to_date('02-OCT-22','DD-MON-RR'));
REM INSERTING into SYSTEM.GS_EVENT
SET DEFINE OFF;
REM INSERTING into SYSTEM."GS_ATHÈTES"
SET DEFINE OFF;
REM INSERTING into SYSTEM.GS_SPONSOR
SET DEFINE OFF;
Insert into SYSTEM.GS_SPONSOR (ID_SPONSOR,NOM,MONTANT,ADRESSMAIL,TYPEDECONTRAT) values ('1','amira',20,'amira@gmail','preium');
Insert into SYSTEM.GS_SPONSOR (ID_SPONSOR,NOM,MONTANT,ADRESSMAIL,TYPEDECONTRAT) values ('2','mahdi',30,'mahdi@gmail.com','premium');
Insert into SYSTEM.GS_SPONSOR (ID_SPONSOR,NOM,MONTANT,ADRESSMAIL,TYPEDECONTRAT) values ('3','uuu',55,'rr','kkk');
Insert into SYSTEM.GS_SPONSOR (ID_SPONSOR,NOM,MONTANT,ADRESSMAIL,TYPEDECONTRAT) values ('4','DDDD',44,'rrr','rrr');
REM INSERTING into SYSTEM.GS_TERRAINS
SET DEFINE OFF;
Insert into SYSTEM.GS_TERRAINS (ID_TERRAIN,NOM,LIEU,CAPACITE,ETAT) values ('AAZ','santiago','madrid',222,'reserve');
Insert into SYSTEM.GS_TERRAINS (ID_TERRAIN,NOM,LIEU,CAPACITE,ETAT) values ('344','FFGDF','EHSH',4332,'8');
Insert into SYSTEM.GS_TERRAINS (ID_TERRAIN,NOM,LIEU,CAPACITE,ETAT) values ('222','HHG','DFGF',33,'4');
--------------------------------------------------------
--  DDL for Index GS_EMPLOYER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."GS_EMPLOYER_PK" ON "SYSTEM"."GS_EMPLOYER" ("ID_EMPLOYE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GS_EMLOYER_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."GS_EMLOYER_UK" ON "SYSTEM"."GS_EMPLOYER" ("NOM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_ATHLETES
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_ATHLETES" ON "SYSTEM"."GS_ATHÈTES" ("ID_ATHLETE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_SPONSOR
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_SPONSOR" ON "SYSTEM"."GS_SPONSOR" ("ID_SPONSOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UK_SPONSOR
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."UK_SPONSOR" ON "SYSTEM"."GS_SPONSOR" ("ADRESSMAIL", "ID_SPONSOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GK_TERRAINS
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."GK_TERRAINS" ON "SYSTEM"."GS_TERRAINS" ("ID_TERRAIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table GS_EMPLOYER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GS_EMPLOYER" ADD CONSTRAINT "GS_EMLOYER_UK" UNIQUE ("NOM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."GS_EMPLOYER" ADD CONSTRAINT "GS_EMPLOYER_PK" PRIMARY KEY ("ID_EMPLOYE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."GS_EMPLOYER" MODIFY ("DATREC" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GS_EMPLOYER" MODIFY ("SALAIRE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GS_EMPLOYER" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GS_EMPLOYER" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GS_EMPLOYER" MODIFY ("ID_EMPLOYE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GS_EVENT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GS_EVENT" MODIFY ("NBPARTICIPANT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GS_EVENT" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GS_EVENT" MODIFY ("COLUMN1" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GS_EVENT" MODIFY ("DATEDEBUT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GS_EVENT" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GS_EVENT" MODIFY ("CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GS_ATHÈTES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GS_ATHÈTES" ADD CONSTRAINT "PK_ATHLETES" PRIMARY KEY ("ID_ATHLETE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."GS_ATHÈTES" MODIFY ("FILIERE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GS_ATHÈTES" MODIFY ("AGE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GS_ATHÈTES" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GS_ATHÈTES" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GS_ATHÈTES" MODIFY ("ID_ATHLETE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GS_SPONSOR
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GS_SPONSOR" ADD CONSTRAINT "GS_SPONSOR_UK_01" UNIQUE ("ADRESSMAIL", "ID_SPONSOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."GS_SPONSOR" ADD CONSTRAINT "GS_SPONSOR_PK_01" PRIMARY KEY ("ID_SPONSOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."GS_SPONSOR" MODIFY ("TYPEDECONTRAT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GS_SPONSOR" MODIFY ("ADRESSMAIL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GS_SPONSOR" MODIFY ("MONTANT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GS_SPONSOR" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GS_SPONSOR" MODIFY ("ID_SPONSOR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GS_TERRAINS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GS_TERRAINS" ADD CONSTRAINT "GK_TERRAINS" PRIMARY KEY ("ID_TERRAIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."GS_TERRAINS" MODIFY ("ETAT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GS_TERRAINS" MODIFY ("CAPACITE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GS_TERRAINS" MODIFY ("LIEU" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GS_TERRAINS" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GS_TERRAINS" MODIFY ("ID_TERRAIN" NOT NULL ENABLE);
